name: Test
on:
  push:
    branches:
      - "main"
  workflow_dispatch:
jobs:
  gvm-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Get latest code
      uses: actions/checkout@v4   

    # Sets up node
    - name: ğŸ§° Setup node
      uses: actions/setup-node@v4
      with:
          node-version: 22

    - name: ğŸ”§ Npm install
      run: npm ci

    # Runs gulp to build
    - name: ğŸ—ï¸ Build with gulp
      run: npx gulp

    - name: ğŸ“© Deploy to custom domain
      uses: SamKirkland/FTP-Deploy-Action@4.3.1
      with:
        server: tajdehart.com     
        username: publish@tajdehart.com
        password: ${{secrets.FTP_PASSWORD}}
        server-dir: tajdehart.com/public_html/
        local-dir: public/
        protocol: ftps
