name: Test
on:
  push:
    branches:
      - "test-*"
jobs:
  gvm-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Get latest code
      uses: actions/checkout@v3   

    # Sets up node
    - name: ğŸ§° Setup node
      uses: actions/setup-node@v1
      with:
          node-version: 16

    - name: ğŸ”§ Npm install
      run: npm ci

    # Runs gulp to build
    - name: ğŸ—ï¸ Build with gulp
      run: gulp

    - name: ğŸ“© Deploy to custom domain
      uses: SamKirkland/FTP-Deploy-Action@4.3.1
      with:
        server: taj.greenvisionmedia.net  
        username: taj@greenvisionmedia.net
        password: ${{secrets.FTP_PASSWORD}}
        server-dir: taj.greenvisionmedia.net/public_html/
        local-dir: public/
        protocol: ftps
